version: '3'

services:
  server:
    restart: unless-stopped
    build: .
    networks:
      - web
    expose:
      - 8001
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:kim.kieranhowland.cc"
      - "traefik.port=8001"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http,https"

networks:
  web:
    external: true