version: '3'

services:
  server:
    restart: unless-stopped
    build: "."
    expose:
      - "8001"
    networks:
      - proxy
      - default
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:kim.kieranhowland.co.uk"
      - "traefik.port=8001"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http,https"
    volumes:
      - /home/main/KIM/uploads:/app/uploads
      - /home/main/KIM/views:/app/views
networks:
  proxy:
    external: true
